### ISSUE TITLE
Bug: CLI doesn't currently pull images if not present

### ISSUE THREAD

**Issue by vdice** [lovethedrake/prototype#3]
Currently, if a target's container image doesn't exist locally, the target will error, as in:
```
 $ drake run build-cli-darwin-amd64

error removing container "": Error: No such container: error creating container "go" for target "build-cli-darwin-amd64": error creating container "kindred-otter-build-cli-darwin-amd64-go": Error: No such image: quay.io/deis/lightweight-docker-go:v0.6.0
```

Therefore, proposing we add the feature of auto-pulling images that don't already exist, perhaps as a default.

**Comment by krancour** [comment]
Total oversight on my part. Didn't notice because, by coincidence, I already had all the images that were used in this project's Drakefile's targets.

**Comment by krancour** [comment]
I'm going to consider this a bug rather than an enhancement.
