### ISSUE TITLE
docs: add steps on first acquiring the drake cli

### ISSUE THREAD

**Issue by vdice** [lovethedrake/prototype#4]
In order to first build/use `drake`, one must have the `drake` cli.  🐔 🥚 

Perhaps add docs on building from source (`go build ...`) and/or, when available, downloading a hosted binary?

**Comment by krancour** [comment]
I'm going to do a v0.1.0 release shortly and I'll publish pre-built binaries and amend the docs to suggest obtaining the Drake CLI from there.

**Comment by krancour** [comment]
I cut a release and added some docs. The docs, for now, are non-exhaustive and pre-suppose some competency with Brigade since Brigade setup (especially for the Github App) is far from easy at present.
